Exit process and format msg for errors in dev mode
serverless/serverless-tencent pull request #107
Opened 2022-01-05 10:55 UTC by timqian

Related ticket: https://app.asana.com/0/1200011502754281/1201504159421230

2022-01-06 02:02 UTC, zongUMR commented
修改的部分可以添加一下单元测试 @timqian

2022-01-06 16:39 UTC, ole3021 requested changes

2022-01-06 16:39 UTC, ole3021 commented on src/commands/dev.js
> +          source: 'Tencent::Debug',
@timqian 这些内容不是要修改掉的内容吗？

2022-01-07 01:58 UTC, timqian commented on src/commands/dev.js
> +          source: 'Tencent::Debug',
已更新

2022-01-07 07:06 UTC, timqian commented
> 修改的部分可以添加一下单元测试 @timqian

@zongUMR 关于你说的单元测试，我看了下，因为改动的这个函数是 dev 命令内部的函数，参考之前的[单元测试](https://github.com/serverless/serverless-tencent/blob/master/tests/commands/dev.test.js)，没有想到很好的测试它的办法，你有什么建议吗

2022-01-07 07:08 UTC, zongUMR commented
> > 修改的部分可以添加一下单元测试 @timqian
> 
> @zongUMR 关于你说的单元测试，我看了下，因为改动的这个函数是 dev 命令内部的函数，参考之前的[单元测试](https://github.com/serverless/serverless-tencent/blob/master/tests/commands/dev.test.js?rgh-link-date=2022-01-07T07%3A06%3A01Z)，没有想到很好的测试它的办法，你有什么建议吗

你可以尝试模拟一下 `startDebug` 的操作，这个操作应该会用到callback函数， 然后让`startDebug` 进行报错和正常运行等操作。

2022-01-07 10:38 UTC, timqian commented
@zongUMR 已添加相关 unit test

2022-01-10 07:26 UTC, zongUMR approved these changes

2022-01-11 07:16 UTC, zongUMR commented on package.json
> -  "version": "3.16.10",
It should be `11 -> 12`, do you forget to pull code?

2022-01-11 07:17 UTC, timqian commented on package.json
> -  "version": "3.16.10",
Just updated the version

2022-01-11 07:21 UTC, zongUMR approved these changes

2022-01-11 10:03 UTC, zongUMR approved these changes

2022-01-12 06:08 UTC, merged