Link instance to existed app in `sls` command
serverless/serverless-tencent pull request #118
Opened 2022-01-13 09:23 UTC by timqian

Closes https://app.asana.com/0/1200011502754281/1201590069760220

## Screenshots

### 1. 当用户没有设置 credentials 时，与原流程一样

### 2. 只有一个 credentials 时（local & global） 

### 3. 多个 credentials 时

### 4. 选择 app 时： 如果用户是第一次部署，提醒用户，并让用户取名

2022-01-17 02:11 UTC, zongUMR commented on src/libs/auto.js
> +          loadTencentGlobalConfig(credentialsPath, { profile: chosenProfile, override: true });
上面已经检测到了 本地有 *key, id*: `const currentCredentials = loadInstanceCredentials();`, 为什么这里还需要读取全局配置呢？我以为是有本地配置先以本地配置为主？

2022-01-17 02:14 UTC, zongUMR commented on src/libs/utils/basic.js
> +      if (!process.env[key] || config.override) {
什么情况下需要用全局配置进行重写？

2022-01-17 02:14 UTC, zongUMR requested changes
添加 `init, auto` 对应的单元测试

2022-01-17 02:47 UTC, timqian commented on src/libs/auto.js
> +          loadTencentGlobalConfig(credentialsPath, { profile: chosenProfile, override: true });
> 上面已经检测到了 本地有 key, id: const currentCredentials = loadInstanceCredentials();

`loadInstanceCredentials` 是从环境变量中找出 key 和 id, 这个 key 和 id 有可能是本地的，也有可能是全局的。

另外，”在用户在当前目录下存在配置，是否要支持用户选择全局 profile“ 这个需要从产品上确定一下  @ole3021 。目前的逻辑是：即使 `sls` 所执行的当前目录下的 `.env` 里面配置了 secrets, 如果用户全局有多个 profile， 用户仍有机会选择 profile。

2022-01-17 02:48 UTC, timqian commented on src/libs/utils/basic.js
> +      if (!process.env[key] || config.override) {
用户可以在 `sls` 命令时选择 profile，可能会与一开始 load 的配置不同

2022-01-17 02:55 UTC, zongUMR commented on src/libs/auto.js
> +          loadTencentGlobalConfig(credentialsPath, { profile: chosenProfile, override: true });
> loadInstanceCredentials 是从环境变量中找出 key 和 id, 这个 key 和 id 有可能是本地的，也有可能是全局的
为什么在本地有 `key, id` 的时候，还可能是全局的呢？ https://github.com/serverless/serverless-tencent/blob/1d047a83d843ecb8617c55e778df670532dac963/src/libs/utils/basic.js?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L814-L818 这个地方的代码因为不会overwrite *process.env* 已经存在的key，那么在已经加在了本地 `.env` 中的`key, id` 之后，应该是不会再用到全局的`key, id` 了吧

2022-01-17 02:58 UTC, ole3021 requested changes

2022-01-17 02:58 UTC, ole3021 commented on src/libs/auto.js
> +          cli.log(`Serverless: ${chalk.yellow('当前账户下未发现 Serverless 项目，请创建新项目')}`);
@timqian  这里是否可以添加用户的当前账户信息，并修改显示消息为

“当前账户 ${accountName} 没有已部署的 Serverless 应用，请检查或创建新项目”

2022-01-17 03:05 UTC, timqian commented on src/libs/auto.js
> +          loadTencentGlobalConfig(credentialsPath, { profile: chosenProfile, override: true });
> 已经加载了本地 .env 中的key, id 之后，应该是不会再用到全局的key, id 了吧
这个是对的。不过如果本地没有 `.env`, 的时候 `loadInstanceCredentials()` 会用到全局的 key 和 id 。因为在最开始有一段 loadGlobalConfig  的逻辑: https://github.com/serverless/serverless-tencent/blob/445459b20c636d202b29ae7b24f78fc411c38885/src/index.js#L16)

我这边想表达的是 `loadInstanceCredentials` 得到的 credentials 是全局还是 .env 是不确定的

2022-01-17 03:18 UTC, timqian commented on src/libs/auto.js
> +          cli.log(`Serverless: ${chalk.yellow('当前账户下未发现 Serverless 项目，请创建新项目')}`);
@ole3021 我看了一下，目前没有  `accountName` 的概念，不过可以获得用户的 appId

2022-01-17 03:30 UTC, timqian commented
@zongUMR `auto` 本身没有看到单元测试，因为是 inteactive 的，我也觉得成本比较高，不考虑添加。
关于 `init` 我会尝试添加一下 `initTemplateFromCli` 这个函数的测试

2022-01-18 02:44 UTC, timqian commented
@zongUMR `initTemplateFromCli` 的测试已添加，替换了 `scf-starter.zip`, 原 zip 解压后生成类似如下目录，新的 zip 没有这个问题
<img width="209" alt="Screen Shot 2022-01-18 at 10 23 14 AM" src="https://user-images.githubusercontent.com/5512552/149861804-132faba3-270c-49bc-9fea-ca95d4cc5bfb.png">

2022-01-18 02:44 UTC, timqian commented on src/libs/auto.js
> +          cli.log(`Serverless: ${chalk.yellow('当前账户下未发现 Serverless 项目，请创建新项目')}`);
已更新：
<img width="594" alt="Screen Shot 2022-01-18 at 10 41 52 AM" src="https://user-images.githubusercontent.com/5512552/149861654-204bbf39-5a60-4ee4-a5ba-095d8e1ce08e.png">

2022-01-18 02:47 UTC, zongUMR commented
> @zongUMR `initTemplateFromCli` 的测试已添加 [1132f05](https://github.com/serverless/serverless-tencent/commit/1132f054dbc39ec47795c38ff15a7ef28a951765)，替换了 `scf-starter.zip`, 原 zip 解压后生成类似如下目录，新的 zip 没有这个问题 (使用了从 cos 下载的 zip) <img alt="Screen Shot 2022-01-18 at 10 23 14 AM" width="209" src="https://user-images.githubusercontent.com/5512552/149861804-132faba3-270c-49bc-9fea-ca95d4cc5bfb.png">

原来的这个zip是我本地把一个`init`之后的项目打包放在里面的

2022-01-18 02:48 UTC, zongUMR approved these changes

2022-01-18 02:53 UTC, merged